### PR TITLE
update to ots 7.1.9

### PR DESCRIPTION
**Pull request by felipesanches**
(issue #4)

### CODE REVIEW

**Comment by anthrotype** [comment]
I’ll take a look today

**Comment by felipesanches** [comment]
thanks!

**Comment by anthrotype** [comment]
i'll pick up from here, thanks

**Comment by anthrotype** [comment]
hmm looks like a know issue in meson when building ots: https://github.com/mesonbuild/meson/issues/5070

@khaledhosny any workarounds?

**Comment by anthrotype** [comment]
I guess we shall pin meson < 0.50 until that issue is fixed upstream

**Comment by khaledhosny** [comment]
Yes, that is what I did for OTS CI build.

**Comment by anthrotype** [comment]
@felipesanches updated packages are up on https://pypi.org/project/opentype-sanitizer/#files

**Comment by felipesanches** [comment]
thanks!

**Pull request merged**
