### PR TITLE
Update OTS to 8.2.2

### PR DESCRIPTION
**Pull request by musicinmybrain**
That’s all!

[Upstream release notes](https://github.com/khaledhosny/ots/releases/tag/v8.2.2)

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]
LGTM, thanks!

**Comment by anthrotype** [comment]
not sure what's wrong, the windows-2016 bot seems stuck forever, maybe something has changed upstream in Github Actions and we need to adapt our config somehow. Will look into it tomorrow

**Comment by josh-hadley** [comment]
https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/

**Comment by anthrotype** [comment]
thanks @josh-hadley

@musicinmybrain can you change it to "windows-latest" as suggested in that doc?

**Pull request merged**
